apiVersion: backup.techmonkeys.se/v1
kind: BackupRequest
metadata:
  name: home-assistant-daily
  namespace: backup
spec:
  sourceNamespace: home-assistant
  sourcePVC: home-assistant-home-assistant
  snapshotClass: vsphere-csi-snapclass
  backupNamespace: backup
  remotePath: "user@starbase:/mnt/backups/home-assistant"
  schedule: "0 3 * * *"
