apiVersion: v1
kind: Service
metadata:
  name: backup-operator-metrics
  namespace: backup-operator
  labels:
    app.kubernetes.io/name: backup-operator
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  selector:
    app.kubernetes.io/name: backup-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backup-operator
  namespace: backup-operator
  labels:
    release: prod-mgmt-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backup-operator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
